/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PomodoroTimerService } from "../pomodoroTimer.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PomodoroTimerCreateInput } from "./PomodoroTimerCreateInput";
import { PomodoroTimer } from "./PomodoroTimer";
import { PomodoroTimerFindManyArgs } from "./PomodoroTimerFindManyArgs";
import { PomodoroTimerWhereUniqueInput } from "./PomodoroTimerWhereUniqueInput";
import { PomodoroTimerUpdateInput } from "./PomodoroTimerUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PomodoroTimerControllerBase {
  constructor(
    protected readonly service: PomodoroTimerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PomodoroTimer })
  @nestAccessControl.UseRoles({
    resource: "PomodoroTimer",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPomodoroTimer(
    @common.Body() data: PomodoroTimerCreateInput
  ): Promise<PomodoroTimer> {
    return await this.service.createPomodoroTimer({
      data: {
        ...data,

        todoItem: data.todoItem
          ? {
              connect: data.todoItem,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        endTime: true,
        id: true,
        startTime: true,

        todoItem: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PomodoroTimer] })
  @ApiNestedQuery(PomodoroTimerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PomodoroTimer",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pomodoroTimers(
    @common.Req() request: Request
  ): Promise<PomodoroTimer[]> {
    const args = plainToClass(PomodoroTimerFindManyArgs, request.query);
    return this.service.pomodoroTimers({
      ...args,
      select: {
        createdAt: true,
        endTime: true,
        id: true,
        startTime: true,

        todoItem: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PomodoroTimer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PomodoroTimer",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pomodoroTimer(
    @common.Param() params: PomodoroTimerWhereUniqueInput
  ): Promise<PomodoroTimer | null> {
    const result = await this.service.pomodoroTimer({
      where: params,
      select: {
        createdAt: true,
        endTime: true,
        id: true,
        startTime: true,

        todoItem: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PomodoroTimer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PomodoroTimer",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePomodoroTimer(
    @common.Param() params: PomodoroTimerWhereUniqueInput,
    @common.Body() data: PomodoroTimerUpdateInput
  ): Promise<PomodoroTimer | null> {
    try {
      return await this.service.updatePomodoroTimer({
        where: params,
        data: {
          ...data,

          todoItem: data.todoItem
            ? {
                connect: data.todoItem,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          endTime: true,
          id: true,
          startTime: true,

          todoItem: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PomodoroTimer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PomodoroTimer",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePomodoroTimer(
    @common.Param() params: PomodoroTimerWhereUniqueInput
  ): Promise<PomodoroTimer | null> {
    try {
      return await this.service.deletePomodoroTimer({
        where: params,
        select: {
          createdAt: true,
          endTime: true,
          id: true,
          startTime: true,

          todoItem: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
